name: Build and Pack FastTrack

on:
  push:
    branches:
      - main
    paths:
      - 'src/FastTrack/**'
      - '.github/workflows/build-fasttrack.yml'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running this workflow'
        type: string
        required: true
        default: Manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Print manual run reason'
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo 'Reason: ${{ github.event.inputs.reason }}'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Ensure packages folder exists and clean only FastTrack package
        run: |
          if [ -d ./packages ]; then
            find ./packages -maxdepth 1 -type f -name 'McpServerToolGenerator.FastTrack.[0-9]*.nupkg' -delete
          else
            mkdir -p ./packages
          fi
        shell: bash

      - name: Restore dependencies for McpServerToolGenerator.FastTrack
        run: dotnet restore src/FastTrack/FastTrack.csproj

      - name: Build McpServerToolGenerator.FastTrack
        run: dotnet build src/FastTrack/FastTrack.csproj --configuration Release --no-restore

      - name: Pack McpServerToolGenerator.FastTrack NuGet package
        run: dotnet pack src/FastTrack/FastTrack.csproj --configuration Release --no-build --output ./packages

      - name: Upload package artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: McpServerToolGenerator.FastTrack
          path: ./packages/*.nupkg
