name: Build and Pack FastTrack.Common

on:
  push:
    branches:
      - main
    paths:
      - 'src/FastTrack.Common/**'
      - '.github/workflows/fasttrack.common-build.yml'
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running this workflow'
        type: string
        required: true
        default: Manual run

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Print manual run reason'
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo 'Reason: ${{ github.event.inputs.reason }}'

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Ensure packages folder exists and is clean
        run: |
          if [ -d ./packages ]; then
            rm -rf ./packages/*
          else
            mkdir -p ./packages
          fi
        shell: bash

      - name: Restore dependencies for McpServerToolGenerator.FastTrack.Common
        run: dotnet restore src/FastTrack.Common/FastTrack.Common.csproj

      - name: Build McpServerToolGenerator.FastTrack.Common
        run: dotnet build src/FastTrack.Common/FastTrack.Common.csproj --configuration Release --no-restore

      - name: Pack McpServerToolGenerator.FastTrack.Common NuGet package
        run: dotnet pack src/FastTrack.Common/FastTrack.Common.csproj --configuration Release --no-build --output ./packages

      - name: Upload package artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: McpServerToolGenerator.FastTrack.Common-nuget-package
          path: ./packages/*.nupkg
