name: PR Validation

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'

jobs:
  build-validation:
    uses: ./.github/workflows/build-validation.yml