name: Release McpServerToolGenerator.FastTrack to NuGet

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (must match .nupkg)'
        required: true
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: McpServerToolGenerator.FastTrack-nuget-package
          path: ./packages

      - name: Publish to NuGet
        run: dotnet nuget push ./packages/McpServerToolGenerator.FastTrack.${{ github.event.inputs.version }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
