name: Release FastTrack.Common to NuGet

on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download package artifact
        uses: actions/download-artifact@v4
        with:
          name: McpServerToolGenerator.FastTrack.Common
          path: ./packages

      - name: Check for package and extract version
        id: extract_version
        run: |
          FILE=$(ls ./packages/McpServerToolGenerator.FastTrack.Common.*.nupkg 2>/dev/null | head -n 1)
          if [ ! -f "$FILE" ]; then
            echo "::error::Package McpServerToolGenerator.FastTrack.Common .nupkg not found in ./packages. Aborting."
            exit 1
          fi
          VERSION=$(echo $FILE | sed -E 's/.*FastTrack.Common\.([0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9]+)?)\.nupkg/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Publish to NuGet
        run: dotnet nuget push ./packages/McpServerToolGenerator.FastTrack.Common.${{ steps.extract_version.outputs.version }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
